"""post to tweet

Revision ID: 89d20e9e92a7
Revises: e556b572e6fb
Create Date: 2021-03-15 14:40:25.941423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89d20e9e92a7'
down_revision = 'e556b572e6fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweet_body'), 'tweet', ['body'], unique=True)
    op.create_index(op.f('ix_tweet_timestamp'), 'tweet', ['timestamp'], unique=False)
    op.drop_index('ix_post_body', table_name='post')
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('body', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='post_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='post_pkey')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.create_index('ix_post_body', 'post', ['body'], unique=True)
    op.drop_index(op.f('ix_tweet_timestamp'), table_name='tweet')
    op.drop_index(op.f('ix_tweet_body'), table_name='tweet')
    op.drop_table('tweet')
    # ### end Alembic commands ###
